version: '3.8'

services:
  websummary-db:
    image: pgvector/pgvector:pg13 #postgres:13
    container_name: websummary-db
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pg3OB!
      POSTGRES_DB: websummary
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - websummarynet

volumes:
  pgdata:
    driver: local

networks:
  websummarynet:
    name: websummarynet
